### ISSUE TITLE
blender 2.8 2d animation layout

### ISSUE THREAD

**Issue by Boo-zi** [ndee85/coa_tools#129] opened 2019-08-13 14:41 UTC
hello. i just installed this add-on and it appears to be working in the 3d view (default layout). but in the 2d animation view the add-on seems to disappear from the menus and can't be accessed.

**Comment by ndee85** [comment] 2019-09-09 20:32
Closing this one. Seems to be related to #133
Also please make sure to test with latest Blender28 branch. I asume this was caused by an error which probably is fixed by now.

**Closed by ndee85** 2019-09-09 20:32 UTC
