### ISSUE TITLE
Slot object not working for me

### ISSUE THREAD

**Issue by rondgrt** [ndee85/coa_tools#85] opened 2018-03-03 08:57 UTC
It is realy unclear to me how i could use the Slot Object feature.

I tried to select multiple sprites, linked to the SpriteObject, and then click on 'Merge to Slot Object'. I end up with an object in the object tree that has an arrow to it (so it is a container). When i click it open it is empty(shows nothing).  In the Blender outliner view only one of the selected png's is visible under the container object.

I would like to switch beteen png's like in the depricated SpriteSheet but realy don't know how it should work.

Could you please expain this with some details how to work with Slot Objects?

Thnks in advance.

**Comment by ndee85** [comment] 2018-03-05 05:37
Yes,
this is how it should work. You select multiple sprites and click merge to slot object. This will combain all sprites into one container. There is a slot index which lets you toggle through the sprites.

If it is not working as intended it may be a bug. Could you please prepare a small file which shocases your problem and I can take a look at it.

**Comment by rondgrt** [comment] 2018-03-09 12:08
Hi,

Thanks for your response. Here are two small blender files that should illustrate the problem i have.

The first (version a) is where i only imported the two png's that i want to combine in a slotobject.
The second (version b) is after i selected the two png's and clicked on 'Merge to Slot Object'.

I am using Blender 2.78c on Windows10 and COA Tools 1.0.2

[blender.zip](https://github.com/ndee85/coa_tools/files/1796783/blender.zip)

**Comment by ndee85** [comment] 2018-03-09 12:22
Ah.. you are using 2.78c.. well thats the problem. Blender 2.79 introduced a new functionality which the slotobjects requiere. You should update to 2.79a which probably should solve your problem.

Tell me if everything works then.

**Comment by rondgrt** [comment] 2018-03-09 12:56
Yes, that was the problem. Works like a charm now.

Thank you for your support, and this great tool for 2D animations in Blender.

**Comment by ndee85** [comment] 2018-03-09 14:33
Ok. Then I'll close this issue.
Glad you like the addon.

**Closed by ndee85** 2018-03-09 14:33 UTC
